project:
  type: website
  output-dir: docs
  execute-dir: project
  
website:
  title: "Evis website"
  navbar:
    left:
      - href: index.qmd
        text: about me
      - href: tab-one/tab-one-index.qmd
        text: Experience
      - href: tab-presentation/presentation-index.qmd
        text: presentation      
      - href: tab-iframe/iframe-index.qmd
        text: iFrame example
    logo: images/lips.jpg 

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

